# Generated by Django 3.2.5 on 2022-04-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220405_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='user2_id',
            field=models.CharField(default=1, max_length=32, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
