# Generated by Django 3.2.5 on 2022-04-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user2_user2_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user2',
            name='user2_id',
        ),
    ]
