# Generated by Django 3.2.5 on 2022-04-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user2_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('numc', models.IntegerField(verbose_name='完型数量')),
                ('numr', models.IntegerField(verbose_name='阅读数量')),
                ('numm', models.IntegerField(verbose_name='单选数量')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '管理员'},
        ),
    ]
